version: '3.7'

services:
    db:
        restart: always
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - ./.env
        ports:
            - 7000:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    api:
        restart: always
        build:
            context: ./
            dockerfile: ./Dockerfile
            args:
                APP_DIR: ${APP_DIR}
                NODE_VERSION: ${NODE_VERSION}
        env_file:
            - ./.env
        ports:
            - 3000:8080
        volumes:
            - ./:/var/www/api-v1
