version: '3.7'

services:
    mysql-db:
        container_name: db
        restart: always
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - ./.env
        ports:
            - 7000:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    server:
        container_name: server
        restart: always
        build:
            context: ./
            dockerfile: ./Dockerfile
            args:
                APP_DIR: ${APP_DIR}
                NODE_VERSION: ${NODE_VERSION}
        env_file:
            - ./.env
        ports:
            - 3000:8080
        volumes:
            - ./:${APP_DIR}
        depends_on:
            - mysql-db

    migration:
        container_name: migration
        image: flyway/flyway
        command: -url=jdbc:mysql://mysql-db -schemas=${MYSQL_DATABASE} -user=${MYSQL_USER} -password=${MYSQL_PASSWORD} -connectRetries=60 migrate
        volumes:
            - ./databases/mysql:/flyway/sql
        depends_on:
            - mysql-db
